### ISSUE TITLE
Webpack5 multi-level @import fails to locate relative asset

### ISSUE THREAD

**Issue by creage** [bholloway/resolve-url-loader#183]
I have a structure
```
index.scss
assets/
   |__style.scss
   |__icons/
      |__icon_red/
         |__icon_red.scss
         |__icon_red.svg
```
**index.scss**
```scss
@import './assets/style.scss';
```
**style.scss**
```scss
@import './icons/icon_red.scss';
```
**icon_red.scss**
```scss
.my_icon {	
    background-image: url('./icon_red.svg');
}
```

Trying to build this style ends up with error
```
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/css-loader/dist/cjs.js):
Error: Can't resolve './icon_red.svg' in 'index.js'
```

**Webpack config**
```js
{
    test: /\.s[ac]ss$/i,
    include: INDEXROOT,
    use: [
        MiniCssExtractPlugin.loader,
        {
            loader: 'css-loader',
            options: {
                importLoaders: 3
            }
        },
        {
            loader: 'postcss-loader',
            options: {
                postcssOptions: {
                    config: ROOT
                }
            }
        },
        {
            loader: 'resolve-url-loader'
        },
        {
            loader: 'sass-loader'
        }
    ]
}
```

**Comment by bholloway** [comment]
Hmm.. strange it works without `sourceMap: true` in `sass-loader`. Doesn't seem to be the problem but I'd eliminate that first in case the loader is note getting a source-map.

I don't recall any actual incompatibilities with Webpack 5 but I have recently added e2e tests in the `v4-development` branch. The `v4` is currently unreleased but there will be a `@next` distag in the next few days🤞. The current `@next` is a little old but you can try it if you like.

Certainly its strange that it works in Webpack 4 but not Weback 5. If you use the `debug` option where does it seem to be looking for the asset?

**Comment by creage** [comment]
Running `@next` with `debug: true` returns me this
```
resolve-url-loader: ./assets/icons/icon_red/icon_red.scss: ./icon_red.svg
  NOT FOUND
```

**Comment by Ragash** [comment]
Hi i've a similiar problem with this config:

>"resolve-url-loader": "^3.1.2",
> "laravel-mix": "^6",
>        "sass": "^1.30.0",
>     "sass-loader": "^10.1.0",
>   "sass-resources-loader": "^2.1.1",

and this structure:

```
resources/
   |__assets/
      |__fonts/
         |__base-text.woff
         |__base-text.woff2
   |__sass/
      |__app.scss
      |__base/
         |__ _fonts.scss
```
             
from my app.scss i just import
`@import "base/fonts";`

and from my _fonts.scss i define:
`@font-face {
    font-family: 'base-text';
    src: url('../../assets/fonts/base-text.woff') format('woff'),
    url('../../assets/fonts/base-text.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
`
relative from the web root (isn't it the point of having resolve-url-loader?)

i use Mix, so my confing is pretty straightfowar:
`mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css');`
    
but it simply blowup:

**ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '../../assets/fonts/base-text.woff' in 'G:\laragon\www\testbug\resources\sass'**

if i change the url making it relative to app.scss (simply removing "../") it will work, but seems that resolve-url-loader simply dont shoot in

**Comment by bholloway** [comment]
@Ragash you would need to check under the hood of mix to see how it's configuring the loader.

Its common for frameworks to use an older version of the loader or configure it using an old `engine` option.

**Comment by evan-krohn** [comment]
Bump. Local configuration:

![image](https://user-images.githubusercontent.com/43254090/112561254-d7d1c780-8da2-11eb-88e0-9e7d10fd0be0.png)

Log:
`C:\something\temp>npm run build

> core-dockerfile-dev-webpack@1.0.0 build C:\something\temp
> webpack --config webpack.config.js

Entrypoint manager =
./src/main.scss 42 bytes (javascript) 1 bytes (asset) [built] [code generated] [1 error]

ERROR in ./src/main.scss
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve './banana.css' in 'C:\something\temp\src'
    at finishWithoutResolve (C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:293:18)
    at C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\something\temp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
    at C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\something\temp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:27:1)
    at C:\something\temp\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:87:43
    at C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\something\temp\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)
    at C:\something\temp\node_modules\enhanced-resolve\lib\Resolver.js:410:5

ERROR in [entry] [initial]
Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at C:\something\temp\node_modules\webpack\lib\asset\AssetModulesPlugin.js:161:29
    at Hook.eval [as call] (eval at create (C:\something\temp\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:12:16)
    at Hook.CALL_DELEGATE [as _call] (C:\something\temp\node_modules\tapable\lib\Hook.js:14:14)
    at Compilation.getRenderManifest (C:\something\temp\node_modules\webpack\lib\Compilation.js:3640:36)
    at C:\something\temp\node_modules\webpack\lib\Compilation.js:3659:22
    at symbolEach (C:\something\temp\node_modules\neo-async\async.js:2444:9)
    at Object.each (C:\something\temp\node_modules\neo-async\async.js:2849:16)
    at Compilation.createChunkAssets (C:\something\temp\node_modules\webpack\lib\Compilation.js:3653:12)
    at C:\something\temp\node_modules\webpack\lib\Compilation.js:2432:14
    at C:\something\temp\node_modules\webpack\lib\Compilation.js:2568:5

webpack 5.27.2 compiled with 2 errors in 602 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! core-dockerfile-dev-webpack@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the core-dockerfile-dev-webpack@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\egame\AppData\Roaming\npm-cache\_logs\2021-03-26T00_46_15_867Z-debug.log
`

Webpack configuration:
`const path = require('path');

module.exports = {
  mode: "development",
  entry: {
    manager: path.resolve(__dirname, 'src/main.scss'),
  },
  module: {
    rules: [
      {
        test: /\.s[ac]ss$/i,//need to add extract-loader, post-css, 
        use: [
          "css-loader",
          {
            loader: "resolve-url-loader",
            options: {
              engine: "postcss"
            }
          },
          {
            loader: "sass-loader",
            options: {
            },
          }
        ],
        type: 'asset/resource',
      },
    ],
  },
};
`

main.scss:
`@use "a/apple";`

apple.scss:
`@import url("./banana.css");`

**Comment by bholloway** [comment]
Closing this due to lack of activity.

Please reopen if this is still a problem @Ragash
