### ISSUE TITLE
karma-webpack crashes

### ISSUE THREAD

**Issue by sagorshkov** [bholloway/resolve-url-loader#59]
Hello. I'm using sass for my styles and I need resolve-url-loader. But I've got a problem with my tests. I'm using Karma to start my unit tests and it's breaking if I use resolve-url-loared. Without the loader, tests start fine.
Logs:  

```
30 05 2017 21:23:31.056:ERROR [karma]: RangeError: Maximum call stack size exceeded
  at RegExp.exec (native)
  at RegExp.[Symbol.match] (native)
  at String.match (native)
  at Object.exports.fromSource (/Users/username/project/node_modules/karma-electron/node_modules/convert-source-map/index.js:122:19)
  at electronPreprocessor (/Users/username/project/node_modules/karma-electron/lib/karma-electron-preprocessor.js:25:38)
  at nextPreprocessor (/Users/username/project/node_modules/karma/lib/preprocessor.js:35:26)
  at /Users/username/project/node_modules/karma-webpack/lib/karma-webpack.js:254:7
  at Plugin.<anonymous> (/Users/username/project/node_modules/karma-webpack/lib/karma-webpack.js:216:9)
  at Plugin.readFile (/Users/username/project/node_modules/karma-webpack/lib/karma-webpack.js:233:5)
  at _combinedTickCallback (internal/process/next_tick.js:73:7)
  at process._tickCallback (internal/process/next_tick.js:104:9)
```

Any ideas about it?

**Comment by bholloway** [comment]
Looks like it can't find a file and is searching too hard (?)

If I recall there is a verbose mode that shows the search path.

**Comment by bholloway** [comment]
Any luck with the verbose mode @sagorshkov?

**Comment by bholloway** [comment]
Closing this due to inactivity.
